name: Inspect Workflow

on:
  workflow_call:
    
jobs:

  download-artifact:
    runs-on: ubuntu-latest
    
    steps:
    - id: download-artifact
      name: Download Artifact
      run: echo "Download Artifact"

  get-workflow-credentials:
    runs-on: ubuntu-latest
    
    steps:
    - id: get-workflow-credentials
      name: Get workflow credentials
      run: echo "Getting workflow credentials"


  setup-inspect-tool:
    runs-on: ubuntu-latest
    
    steps:
    - id: setup-inspect-tool
      name: Set-up Inspect Tool
      run: echo "Set-up Inspect Tool"


  inspect:
    runs-on: ubuntu-latest
    
    steps:
    - id: inspect
      name: Inspect
      run: echo "Run Inspect"

  
  emit-inspect-event:
    runs-on: ubuntu-latest
    
    steps:
    - id: emit-inspect-event
      name: Emit inspect event
      run: echo "Emit inspect event"

