name: Release Workflow
run-name: Release Workflow
on:
  workflow_call:

jobs:
  build-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/build-workflow.yml@main
    name: Build Stage
  unit-test-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/unit-test-workflow.yml@main
    name: Unit Test Stage
    needs: build-stage
  inspect-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/inspect-workflow.yml@main
    name: Inspect Stage
    needs: unit-test-stage
  sast-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/sast-workflow.yml@main
    name: SAST Stage
    needs: inspect-stage
  sca-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/sca-workflow.yml@main
    name: SCA Stage
    needs: inspect-stage
  threadfix-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/threadfix-workflow.yml@main
    name: Threadfix Stage
    needs: [ sast-stage, sca-stage ]
  publish-artifact-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/publish-artifact-workflow.yml@main
    name: Publish Artifact Stage
    needs: threadfix-stage
  create-image-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/create-image-workflow.yml@main
    name: Create Image Stage
    needs: publish-artifact-stage
  scan-image-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/scan-image-workflow.yml@main
    name: Scan Image Stage
    needs: create-image-stage
  code-sign-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/code-sign-workflow.yml@main
    name: Code Sign Stage
    needs: scan-image-stage
  publish-image-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/publish-image-workflow.yml@main
    name: Publish Image Stage
    needs: code-sign-stage
  deploy-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/deploy-workflow.yml@main
    name: Deploy Stage
    needs: publish-image-stage
  notification-stage:
    uses: pilotaccount-org/reusable-workflows/.github/workflows/notification-workflow.yml@main
    name: Notification Stage
    needs: deploy-stage
