name: Release Reusable Workflow
run-name: Release Reusable Workflow
on:
  workflow_call:

jobs:
  build-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/build-workflow.yml@main
  unit-test-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/unit-test-workflow.yml@main
    needs: build-workflow
  inspect-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/inspect-workflow.yml@main
    needs: unit-test-workflow
  sast-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/sast-workflow.yml@main
    needs: inspect-workflow
  sca-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/sca-workflow.yml@main
    needs: inspect-workflow
  threadfix-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/threadfix-workflow.yml@main
    needs: [ sast-workflow, sca-workflow ]
  publish-artifact-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/publish-artifact-workflow.yml@main
    needs: threadfix-workflow
  create-image-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/create-image-workflow.yml@main
    needs: publish-artifact-workflow
  scan-image-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/scan-image-workflow.yml@main
    needs: create-image-workflow
  code-sign-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/code-sign-workflow.yml@main
    needs: scan-image-workflow
  publish-image-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/publish-image-workflow.yml@main
    needs: code-sign-workflow
  deploy-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/deploy-workflow.yml@main
    needs: publish-image-workflow
  notification-workflow:
    uses: pilotaccount-org/app-dev-repo-for-workflow-test/.github/workflows/notification-workflow.yml@main
    needs: deploy-workflow
  
