name: SAST Workflow

on:
  workflow_call:
    
jobs:

  download-artifact:
    runs-on: ubuntu-latest
    
    steps:
    - id: download-artifact
      name: Download Artifact
      run: echo "Download Artifact"

  get-workflow-credentials:
    runs-on: ubuntu-latest
    
    steps:
    - id: get-workflow-credentials
      name: Get workflow credentials
      run: echo "Getting workflow credentials"


  get-jdk:
    runs-on: ubuntu-latest
    
    steps:
    - id: get-jdk
      name: Get JDK
      run: echo "Get JDK"


  setup-sast-tool:
    runs-on: ubuntu-latest
    
    steps:
    - id: setup-sast-tool
      name: Set-up SAST Tool
      run: echo "Set-up SAST Tool"


  sast-scan:
    runs-on: ubuntu-latest
    
    steps:
    - id: unit-test
      name: Unit Test
      run: echo "Run Unit Test"

  
  emit-sast-scan-event:
    runs-on: ubuntu-latest
    
    steps:
    - id: emit-sast-scan-event
      name: Emit sast scan event
      run: echo "Emit sast scan event"

