name: Unit Test Stage
run-name: Unit Test Stage

on:
  workflow_call:
    
jobs:

  download-artifact:
    runs-on: ubuntu-latest
    name: Download Artifact
    steps:
    - id: download-artifact
      name: Download Artifact
      run: echo "Download Artifact"

  get-workflow-credentials:
    runs-on: ubuntu-latest
    name: Get workflow credentials
    
    steps:
    - id: get-workflow-credentials
      name: Get workflow credentials
      run: echo "Getting workflow credentials"


  get-jdk:
    runs-on: ubuntu-latest
    name: Get JDK
    
    steps:
    - id: get-jdk
      name: Get JDK
      run: echo "Get JDK"


  get-gradle:
    runs-on: ubuntu-latest
    name: Get Gradle
    
    steps:
    - id: get-gradle
      name: Get Gradle
      run: echo "Get Gradle"


  unit-test:
    runs-on: ubuntu-latest
    name: Unit Test
    
    steps:
    - id: unit-test
      name: Unit Test
      run: echo "Run Unit Test"

  
  emit-unit-test-event:
    runs-on: ubuntu-latest
    name: Emit unit test event
    
    steps:
    - id: emit-unit-test-event
      name: Emit unit test event
      run: echo "Emit unit test event"

